<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>プライバシーポリシー | Web Learning</title>
        @include('layouts.partials.pwa-head')
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="min-h-screen bg-[#F7F5F0] text-[#171717] antialiased dark:bg-[#171717] dark:text-stone-100">
        <header class="border-b border-stone-200 dark:border-stone-800">
            <div class="mx-auto flex max-w-4xl items-center justify-between gap-5 px-5 py-5 sm:px-8">
                <a href="{{ url('/') }}" class="text-lg font-semibold tracking-tight focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9]"><span class="text-[#3155D9]">web</span><span> learning</span><span class="text-[#3155D9]">.</span></a>
                @guest
                    <a href="{{ route('login') }}" class="text-sm font-medium text-stone-600 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-300">ログイン</a>
                @else
                    <a href="{{ route('dashboard') }}" class="text-sm font-medium text-stone-600 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-300">Dashboardへ</a>
                @endguest
            </div>
        </header>

        <main class="mx-auto max-w-4xl px-5 py-14 sm:px-8 sm:py-20">
            <article class="mx-auto max-w-3xl">
                {{-- TODO: 公開前に制定日・最終改定日を設定する。 --}}
                <p class="text-xs font-semibold tracking-[0.18em] text-[#3155D9]">PRIVACY POLICY</p>
                <h1 class="mt-4 font-editorial text-3xl font-semibold tracking-tight sm:text-4xl">プライバシーポリシー</h1>
                <p class="mt-5 max-w-2xl text-sm leading-7 text-stone-600 dark:text-stone-300 sm:text-base">Web Learningにおける利用者情報の取り扱いについて定めています。</p>

                <nav class="mt-12 border-y border-stone-300 py-6 dark:border-stone-700" aria-label="プライバシーポリシー目次">
                    <h2 class="text-sm font-semibold text-[#171717] dark:text-white">目次</h2>
                    <ol class="mt-4 grid gap-x-8 gap-y-3 text-sm leading-6 sm:grid-cols-2">
                        @foreach ([['information', '1. 取得する情報'], ['purpose', '2. 利用目的'], ['services', '3. 外部サービスの利用'], ['sharing', '4. 第三者への提供・外部委託'], ['security', '5. 安全管理'], ['retention', '6. 保存期間'], ['deletion', '7. アカウント・データ削除'], ['choices', '8. 利用者による選択'], ['minors', '9. 未成年者'], ['changes', '10. ポリシーの変更'], ['contact', '11. お問い合わせ']] as [$id, $label])
                            <li><a href="#{{ $id }}" class="text-[#3155D9] underline decoration-[#3155D9]/30 underline-offset-4 transition hover:text-[#2848bd] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9]">{{ $label }}</a></li>
                        @endforeach
                    </ol>
                </nav>

                <div class="mt-14 space-y-14 text-sm leading-7 text-stone-700 dark:text-stone-300 sm:text-base sm:leading-8">
                    <section aria-labelledby="introduction"><p id="introduction">Web Learning（以下「本サービス」といいます。）の運営者（以下「運営者」といいます。）は、本サービスおよびChrome拡張機能の提供にあたり取得する利用者の情報について、以下のとおりプライバシーポリシーを定めます。</p></section>

                    <section id="information" aria-labelledby="information-heading">
                        <h2 id="information-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第1条　取得する情報</h2>
                        <p class="mt-5">本サービスでは、サービスの提供に必要な範囲で、以下の情報を取得することがあります。</p>
                        <div class="mt-8 space-y-9">
                            <section aria-labelledby="account-information"><h3 id="account-information" class="text-lg font-semibold text-[#171717] dark:text-white">1. アカウント情報</h3><ul class="mt-3 list-disc space-y-1 pl-6"><li>氏名または表示名</li><li>メールアドレス</li><li>パスワード</li><li>Googleアカウント識別情報</li><li>メールアドレスの確認状態</li><li>アカウント作成日時、更新日時</li><li>オンボーディングの完了状況</li></ul><p class="mt-4">パスワードはハッシュ化して保存し、平文のパスワードを保存しません。</p></section>
                            <section aria-labelledby="google-information"><h3 id="google-information" class="text-lg font-semibold text-[#171717] dark:text-white">2. Googleログインにより取得する情報</h3><p class="mt-3">Googleアカウントを利用してログインする場合、本サービスはGoogleから以下の情報を取得します。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>Googleアカウントを識別するID</li><li>氏名または表示名</li><li>メールアドレス</li><li>メールアドレスの確認状態</li></ul><p class="mt-4">本サービスでは、Googleログインのために取得したアクセストークンまたはリフレッシュトークンを継続的に保存しません。</p><p class="mt-4">また、Gmail、Google Drive、Google Calendar等のデータへアクセスする権限は要求しません。</p></section>
                            <section aria-labelledby="learning-data"><h3 id="learning-data" class="text-lg font-semibold text-[#171717] dark:text-white">3. 学習データ</h3><p class="mt-3">本サービスの利用に伴い、以下の情報を保存することがあります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>学習セット</li><li>学習セットのタイトル、分野、トピック</li><li>問題文</li><li>選択肢</li><li>正解</li><li>解説</li><li>回答履歴</li><li>復習履歴</li><li>学習進捗</li><li>保存した用語</li><li>用語の説明</li><li>ユーザーが作成したカテゴリ</li><li>Web学習リスト</li><li>学習に使用したWebページのURL、タイトル、ホスト名</li><li>AIによって抽出された用語および説明</li></ul></section>
                            <section aria-labelledby="extension-information"><h3 id="extension-information" class="text-lg font-semibold text-[#171717] dark:text-white">4. Chrome拡張機能から取得する情報</h3><p class="mt-3">利用者がChrome拡張機能のLearning ModeをONにした場合、本サービスは学習候補を抽出するため、閲覧中のWebページから以下の情報を取得することがあります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>画面上に表示された文章</li><li>ページタイトル</li><li>ページURL</li><li>ホスト名</li></ul><p class="mt-4">文章については、主に画面上に表示された見出し、段落、リスト等を対象とします。</p><p class="mt-4">本サービスは、Learning Modeによる解析を目的として、ページ全体のHTML、Cookie、パスワード入力欄、フォームに入力した内容を収集することを目的としていません。</p><p class="mt-4">ただし、Webページ上に個人情報その他の機微な情報が通常の本文として表示されている場合、その表示された文章が解析対象に含まれる可能性があります。</p><p class="mt-4">利用者はChrome拡張機能から特定のWebサイトを学習対象外として設定することができます。</p></section>
                            <section aria-labelledby="web-analysis"><h3 id="web-analysis" class="text-lg font-semibold text-[#171717] dark:text-white">5. Webページ解析に関する情報</h3><p class="mt-3">Chrome拡張機能から取得したWebページの文章、ページタイトルおよびURLは、学習候補を生成するためGoogle Gemini APIへ送信されます。</p><p class="mt-4">解析後、本サービスのWeb学習リストには主に以下を保存します。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>ページタイトル</li><li>URL</li><li>ホスト名</li><li>抽出された用語</li><li>用語の説明</li></ul><p class="mt-4">Webページの本文全文をWeb学習リストのデータベースへ恒久的に保存することを目的としていません。</p></section>
                            <section aria-labelledby="screenshot"><h3 id="screenshot" class="text-lg font-semibold text-[#171717] dark:text-white">6. スクリーンショット学習</h3><p class="mt-3">利用者がスクリーンショット学習を利用した場合、アップロードされた画像を学習候補の抽出に使用します。</p><p class="mt-4">アップロードされた画像は、本サービスの非公開ストレージへ保存され、画像解析のためGoogle Gemini APIへ送信されます。</p><p class="mt-4">画像から抽出された用語、説明、問題等は、利用者の学習データとして保存される場合があります。</p></section>
                            <section aria-labelledby="ai-information"><h3 id="ai-information" class="text-lg font-semibold text-[#171717] dark:text-white">7. AI機能で利用する情報</h3><p class="mt-3">本サービスでは、Google Gemini APIを使用して以下の処理を行います。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>Webページからの学習候補抽出</li><li>スクリーンショット画像の解析</li><li>問題生成</li><li>解説生成</li><li>学習中のAI質問への回答</li><li>用語説明の生成</li></ul><p class="mt-4">機能に応じて、以下の情報をGoogle Gemini APIへ送信する場合があります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>Webページ上の文章</li><li>ページタイトル</li><li>URL</li><li>アップロードされた画像</li><li>学習用語</li><li>用語の説明</li><li>問題文</li><li>解説</li><li>利用者がAIへ入力した質問</li></ul><p class="mt-4">本サービスは、通常のAI処理において、利用者のパスワード、GoogleアカウントID、Stripeの決済情報、Extension Access Token、Laravelのセッション情報をGeminiへ送信することを目的としていません。</p></section>
                            <section aria-labelledby="ai-usage"><h3 id="ai-usage" class="text-lg font-semibold text-[#171717] dark:text-white">8. AI利用状況</h3><p class="mt-3">サービス提供、利用上限管理、障害調査および費用管理のため、以下のAI利用情報を保存することがあります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>利用者ID</li><li>利用したAI機能</li><li>利用したAIモデル</li><li>入力文字数</li><li>入力・出力トークン数</li><li>処理成功の有無</li><li>HTTPステータス</li><li>エラー情報</li><li>利用日時</li></ul><p class="mt-4">通常、AIへ送信したプロンプト全文やAI回答全文を利用状況ログとして保存することを目的としていません。</p></section>
                            <section aria-labelledby="payment"><h3 id="payment" class="text-lg font-semibold text-[#171717] dark:text-white">9. 決済およびサブスクリプション情報</h3><p class="mt-3">有料プランの決済にはStripeを利用します。</p><p class="mt-4">本サービスでは、Stripeとの連携のため以下の情報を保存する場合があります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>Stripe顧客ID</li><li>サブスクリプションID</li><li>契約状態</li><li>契約している料金プラン</li><li>支払方法の種類</li><li>カード番号の下4桁</li><li>契約開始・終了等に関する情報</li></ul><p class="mt-4">クレジットカード番号全体、CVC等のカード認証情報は、Stripeの決済画面で処理され、本サービスが直接保存することを目的としていません。</p></section>
                            <section aria-labelledby="cookies"><h3 id="cookies" class="text-lg font-semibold text-[#171717] dark:text-white">10. Cookie、セッションおよびブラウザ情報</h3><p class="mt-3">本サービスでは、ログイン状態の維持、セキュリティ、不正利用防止等のため、Cookieやセッションを使用します。</p><p class="mt-4">利用環境によって、以下の情報が記録されることがあります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>セッション識別情報</li><li>ユーザーID</li><li>IPアドレス</li><li>User-Agent</li><li>最終アクセス時刻</li></ul><p class="mt-4">これらはログイン状態の維持、セキュリティ、不正アクセス防止等に利用されます。</p></section>
                            <section aria-labelledby="extension-storage"><h3 id="extension-storage" class="text-lg font-semibold text-[#171717] dark:text-white">11. Chrome拡張機能内に保存する情報</h3><p class="mt-3">Chrome拡張機能では、機能提供のため利用者のブラウザ内に以下の情報を保存することがあります。</p><ul class="mt-3 list-disc space-y-1 pl-6"><li>Web Learningとの接続情報</li><li>Learning ModeのON/OFF</li><li>学習対象外に設定したWebサイト</li><li>直近の解析結果</li><li>ページURL、タイトル</li><li>抽出された学習候補</li><li>通知に必要な情報</li><li>一時的な接続情報</li></ul><p class="mt-4">これらはChromeのstorage機能を利用して保存されます。</p></section>
                        </div>
                    </section>

                    <section id="purpose" aria-labelledby="purpose-heading"><h2 id="purpose-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第2条　利用目的</h2><p class="mt-5">運営者は、取得した情報を以下の目的で利用します。</p><ol class="mt-4 list-decimal space-y-1 pl-6"><li>本サービスのアカウントを作成・管理するため</li><li>利用者本人を認証するため</li><li>Googleログインを提供するため</li><li>Chrome拡張機能とWeb Learningを接続するため</li><li>Webページから学習候補を生成するため</li><li>スクリーンショットから学習候補を生成するため</li><li>問題、解説その他の学習コンテンツを生成するため</li><li>学習履歴、復習予定および学習進捗を管理するため</li><li>AIを利用した学習支援機能を提供するため</li><li>有料プランの契約、決済および解約を管理するため</li><li>利用上限を管理するため</li><li>お問い合わせへの対応を行うため</li><li>不正利用・不正アクセスを防止するため</li><li>障害調査およびサービス改善を行うため</li><li>本サービスの重要なお知らせを行うため</li><li>法令上必要な対応を行うため</li></ol></section>

                    <section id="services" aria-labelledby="services-heading"><h2 id="services-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第3条　外部サービスの利用</h2><p class="mt-5">本サービスでは、以下の外部サービスを利用します。</p><div class="mt-8 space-y-8"><section><h3 class="text-lg font-semibold text-[#171717] dark:text-white">1. Google</h3><p class="mt-3">Googleログインの本人認証、およびGoogle Gemini APIによるAI処理に利用します。</p><p class="mt-4">Google Gemini APIへ送信される情報については、本ポリシー第1条に記載するとおりです。</p></section><section><h3 class="text-lg font-semibold text-[#171717] dark:text-white">2. Stripe</h3><p class="mt-3">有料プランの決済、サブスクリプション管理、支払方法の管理等に利用します。</p><p class="mt-4">カード情報等の決済情報については、Stripeがそのプライバシーポリシーに基づいて取り扱います。</p></section><section><h3 class="text-lg font-semibold text-[#171717] dark:text-white">3. OpenAI ChatGPT</h3><p class="mt-3">本サービス内の「ChatGPTに聞く」機能を利用者が明示的に選択した場合、選択した文章をもとに作成した質問内容がChatGPTへ送信されます。</p><p class="mt-4">この機能は利用者自身が操作した場合にのみ実行されます。</p></section><section><h3 class="text-lg font-semibold text-[#171717] dark:text-white">4. その他のサービス</h3><p class="mt-3">本サービスでは、Webフォント配信、メール送信等のため、第三者サービスを利用する場合があります。</p></section></div></section>

                    <section id="sharing" aria-labelledby="sharing-heading"><h2 id="sharing-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第4条　第三者への提供および外部委託</h2><p class="mt-5">運営者は、法令で認められる場合を除き、利用者の個人情報を本人の同意なく、利用目的と無関係な第三者へ販売することはありません。</p><p class="mt-4">ただし、本サービスの提供に必要な範囲で、Google、Stripe、メール配信事業者等の外部サービスを利用する場合があります。</p><p class="mt-4">これらの事業者には、本サービスの提供に必要な範囲で情報が送信されることがあります。</p><p class="mt-4">また、これらの外部サービスでは、利用者の情報が日本国外で処理または保存される可能性があります。</p><p class="mt-4">各事業者における情報の取扱いについては、各社のプライバシーポリシー等をご確認ください。</p></section>

                    <section id="security" aria-labelledby="security-heading"><h2 id="security-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第5条　情報の安全管理</h2><p class="mt-5">運営者は、取得した情報について、漏えい、滅失、毀損、不正アクセス等を防止するため、必要かつ適切な安全管理措置を講じます。</p><p class="mt-4">本サービスでは、例えば以下の対策を行います。</p><ul class="mt-4 list-disc space-y-1 pl-6"><li>パスワードのハッシュ化</li><li>CSRF対策</li><li>Google OAuthのstate検証</li><li>ユーザーごとのデータ所有権確認</li><li>Chrome拡張機能用トークンのハッシュ保存</li><li>Stripe Webhookの署名検証</li><li>アクセス回数・AI利用回数の制限</li><li>アップロードファイルの形式および容量確認</li></ul></section>

                    <section id="retention" aria-labelledby="retention-heading"><h2 id="retention-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第6条　情報の保存期間</h2><p class="mt-5">取得した情報は、本サービスの提供に必要な期間、または法令上必要な期間保存します。</p><p class="mt-4">アカウントに関連する学習データは、原則として利用者が削除するまで保存されます。</p><p class="mt-4">一部の学習データについては、誤操作から復元できるようSoft Delete方式で一定期間保持する場合があります。</p><p class="mt-4">Chrome拡張機能の接続に使用する一時情報等については、短期間で失効するものがあります。</p><p class="mt-4">本サービスでは、サービス運営上必要な範囲を超えて情報を保持し続けないよう努めます。</p></section>

                    <section id="deletion" aria-labelledby="deletion-heading"><h2 id="deletion-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第7条　アカウントおよびデータの削除</h2><p class="mt-5">利用者は、本サービスで提供される方法により、自身の学習データまたはアカウントを削除することができます。</p><p class="mt-4">アカウント削除時には、利用者に関連する個人情報および学習データについて、法令上またはサービス運営上保持が必要な情報を除き、削除または個人を識別できない状態にするよう努めます。</p><p class="mt-4">復元機能を提供しているデータについては、通常の削除操作後も一定期間保存される場合があります。</p><p class="mt-4">Stripe等の外部サービスが保持する情報については、各外部サービスの保持方針が適用される場合があります。</p></section>

                    <section id="choices" aria-labelledby="choices-heading"><h2 id="choices-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第8条　利用者による選択</h2><p class="mt-5">利用者は、Chrome拡張機能のLearning ModeをいつでもOFFにすることができます。</p><p class="mt-4">また、特定のWebサイトを学習対象外として設定することができます。</p><p class="mt-4">Learning ModeがOFFの場合、新たなWebページ解析は行いません。</p></section>

                    <section id="minors" aria-labelledby="minors-heading"><h2 id="minors-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第9条　未成年者の利用</h2><p class="mt-5">未成年者が本サービスを利用する場合は、必要に応じて保護者等の法定代理人の同意を得たうえで利用してください。</p></section>

                    <section id="changes" aria-labelledby="changes-heading"><h2 id="changes-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第10条　本ポリシーの変更</h2><p class="mt-5">運営者は、法令の改正、サービス内容の変更等に応じて、本ポリシーを変更することがあります。</p><p class="mt-4">重要な変更を行う場合には、本サービス上その他適切な方法で利用者へ通知します。</p></section>

                    <section id="contact" aria-labelledby="contact-heading"><h2 id="contact-heading" class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第11条　お問い合わせ</h2><p class="mt-5">本ポリシーまたは個人情報の取扱いに関するお問い合わせは、以下の窓口までご連絡ください。</p><div class="mt-5 space-y-3 border-l-2 border-[#3155D9] pl-5"><!-- TODO: 公開前に運営者名を設定 --><p><span class="font-semibold text-[#171717] dark:text-white">運営者名：</span>[運営者名]</p><p><span class="font-semibold text-[#171717] dark:text-white">サービス名：</span>Web Learning</p><!-- TODO: 公開前に問い合わせ用メールアドレスを設定 --><p><span class="font-semibold text-[#171717] dark:text-white">お問い合わせ先：</span>[問い合わせ用メールアドレス]</p><!-- TODO: 公開前に所在地を設定（必要に応じて記載） --><p><span class="font-semibold text-[#171717] dark:text-white">所在地：</span>[必要に応じて記載]</p></div></section>
                </div>
            </article>
        </main>
        <footer class="border-t border-stone-200 px-5 py-8 dark:border-stone-800 sm:px-8"><nav class="mx-auto flex max-w-3xl flex-wrap justify-center gap-x-5 gap-y-2 text-xs" aria-label="法務ページ"><a href="{{ route('terms') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">利用規約</a><a href="{{ route('privacy') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">プライバシーポリシー</a><a href="{{ route('tokushoho') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">特定商取引法に基づく表記</a></nav></footer>
    </body>
</html>
