<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>利用規約 | Web Learning</title>
        @include('layouts.partials.pwa-head')
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="min-h-screen bg-[#F7F5F0] text-[#171717] antialiased dark:bg-[#171717] dark:text-stone-100">
        <header class="border-b border-stone-200 dark:border-stone-800"><div class="mx-auto flex max-w-4xl items-center justify-between gap-5 px-5 py-5 sm:px-8"><a href="{{ url('/') }}" class="text-lg font-semibold tracking-tight focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9]"><span class="text-[#3155D9]">web</span><span> learning</span><span class="text-[#3155D9]">.</span></a>@guest<a href="{{ route('login') }}" class="text-sm font-medium text-stone-600 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-300">ログイン</a>@else<a href="{{ route('dashboard') }}" class="text-sm font-medium text-stone-600 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-300">Dashboardへ</a>@endguest</div></header>
        <main class="mx-auto max-w-4xl px-5 py-14 sm:px-8 sm:py-20"><article class="mx-auto max-w-3xl">
            {{-- TODO: 公開前に制定日・最終改定日を設定する。 --}}
            <p class="text-xs font-semibold tracking-[0.18em] text-[#3155D9]">TERMS OF SERVICE</p><h1 class="mt-4 font-editorial text-3xl font-semibold tracking-tight sm:text-4xl">利用規約</h1><p class="mt-5 max-w-2xl text-sm leading-7 text-stone-600 dark:text-stone-300 sm:text-base">Web Learningをご利用いただく際の条件について定めています。</p>
            <nav class="mt-12 border-y border-stone-300 py-6 dark:border-stone-700" aria-label="利用規約目次"><h2 class="text-sm font-semibold text-[#171717] dark:text-white">目次</h2><ol class="mt-4 grid gap-x-8 gap-y-3 text-sm leading-6 sm:grid-cols-2">@foreach ([['scope', '第1条　適用'], ['service', '第2条　本サービスの内容'], ['account', '第3条　アカウント登録'], ['google', '第4条　Googleログイン'], ['extension', '第5条　Chrome拡張機能'], ['ai', '第6条　AI機能'], ['content', '第7条　利用者が使用するコンテンツ'], ['prohibited', '第8条　禁止事項'], ['free', '第9条　Freeプラン'], ['plus', '第10条　Plusプラン'], ['renewal', '第11条　Plusの契約および自動更新'], ['cancellation', '第12条　Plusの解約'], ['refunds', '第13条　返金'], ['payment', '第14条　決済'], ['changes', '第15条　サービスの変更・停止'], ['external', '第16条　外部サービス'], ['intellectual-property', '第17条　知的財産権'], ['restriction', '第18条　利用制限・アカウント停止'], ['deletion', '第19条　アカウント削除'], ['disclaimer', '第20条　免責等'], ['privacy', '第21条　プライバシー'], ['terms-changes', '第22条　本規約の変更'], ['severability', '第23条　分離可能性'], ['governing-law', '第24条　準拠法'], ['jurisdiction', '第25条　管轄'], ['contact', '第26条　お問い合わせ']] as [$id, $label])<li><a href="#{{ $id }}" class="text-[#3155D9] underline decoration-[#3155D9]/30 underline-offset-4 transition hover:text-[#2848bd] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9]">{{ $label }}</a></li>@endforeach</ol></nav>
            <div class="mt-14 space-y-14 text-sm leading-7 text-stone-700 dark:text-stone-300 sm:text-base sm:leading-8">
                <section><p>この利用規約（以下「本規約」といいます。）は、Web Learning（以下「本サービス」といいます。）の運営者（以下「運営者」といいます。）が提供する本サービスおよびChrome拡張機能の利用条件を定めるものです。</p><p class="mt-4">利用者は、本規約の内容を確認し、これに同意したうえで本サービスを利用するものとします。</p></section>
                <section id="scope"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第1条　適用</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本規約は、本サービスの利用に関する運営者と利用者との間の一切の関係に適用されます。</li><li>本サービス上で掲載する利用方法、注意事項、個別のルールその他の表示は、本規約の一部を構成する場合があります。</li><li>本規約と個別の表示内容が異なる場合には、個別に明示した条件を優先するものとします。</li></ol></section>
                <section id="service"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第2条　本サービスの内容</h2><p class="mt-5">本サービスは、Webページ、スクリーンショットその他の情報を利用して、学習候補、問題、解説等を作成・保存し、学習および復習を支援するサービスです。</p><p class="mt-4">主な機能には以下を含みます。</p><ul class="mt-4 list-disc space-y-1 pl-6"><li>Chrome拡張機能を利用したWebページ解析</li><li>Webページからの学習候補抽出</li><li>スクリーンショットからの学習候補抽出</li><li>問題および解説の生成</li><li>学習セットの保存</li><li>学習履歴および復習管理</li><li>用語の保存</li><li>AIを利用した学習支援</li><li>その他運営者が提供する関連機能</li></ul><p class="mt-4">機能の内容は追加、変更または終了される場合があります。</p></section>
                <section id="account"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第3条　アカウント登録</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本サービスの一部機能を利用するには、アカウント登録が必要です。</li><li>利用者は、正確かつ最新の情報を登録するものとします。</li><li>利用者は、自らのアカウントおよび認証情報を適切に管理する責任を負います。</li><li>アカウントを第三者に譲渡、貸与または共有してはなりません。</li><li>運営者は、登録内容に虚偽がある場合、不正利用が確認された場合、その他本規約に違反した場合には、アカウントの利用を制限することがあります。</li></ol></section>
                <section id="google"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第4条　Googleログイン</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本サービスではGoogleアカウントを利用したログイン方法を提供する場合があります。</li><li>Googleログインの利用には、Googleが定める利用条件等も適用されます。</li><li>Googleアカウント自体の管理については利用者自身が責任を負うものとします。</li></ol></section>
                <section id="extension"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第5条　Chrome拡張機能</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本サービスはChrome拡張機能を通じてWebページから学習候補を生成する機能を提供します。</li><li>Learning ModeがONの場合、閲覧中のWebページに表示された文章、ページタイトル、URL等が学習候補生成のために処理されることがあります。</li><li>利用者は特定のWebサイトを学習対象外として設定することができます。</li><li>利用者は、個人情報、機密情報その他第三者へ送信すべきでない情報が表示されているページについて、必要に応じてLearning ModeをOFFにするまたは対象外設定を行うものとします。</li><li>Chrome、ブラウザ、Webサイト等の仕様変更により、拡張機能の一部または全部が一時的に利用できなくなる場合があります。</li></ol></section>
                <section id="ai"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第6条　AI機能</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本サービスではGoogle Gemini API等のAI技術を利用して、学習候補、問題、解説その他の内容を生成します。</li><li>AIによって生成される内容について、正確性、完全性、最新性、特定目的への適合性を保証するものではありません。</li><li>AIが生成した問題・解説等には、誤り、不正確な内容または不適切な内容が含まれる場合があります。</li><li>利用者は、重要な判断、試験、業務その他正確性が特に求められる場面において、必要に応じて信頼できる資料等を確認するものとします。</li><li>本サービスのAI生成結果のみを根拠として行った判断について、法令上認められる範囲を除き、運営者はその結果を保証するものではありません。</li></ol></section>
                <section id="content"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第7条　利用者が使用するコンテンツ</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>利用者は、本サービスへ入力、アップロードまたは解析させるWebページ、画像、文章その他のコンテンツについて、本サービスで利用するために必要な権利または権限を有していることを確認するものとします。</li><li>利用者は、著作権、商標権、プライバシー権その他の第三者の権利を侵害する目的で本サービスを利用してはなりません。</li><li>利用者が第三者の情報を取り扱う場合には、法令および当該サービスの利用条件等を遵守してください。</li><li>本サービスは、著作物その他の情報について利用者に新たな権利を付与するものではありません。</li></ol></section>
                <section id="prohibited"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第8条　禁止事項</h2><p class="mt-5">利用者は、以下の行為を行ってはなりません。</p><ul class="mt-4 list-disc space-y-1 pl-6"><li>法令または公序良俗に違反する行為</li><li>犯罪行為に関連する行為</li><li>第三者の権利を侵害する行為</li><li>他人になりすます行為</li><li>アカウントを不正に利用する行為</li><li>不正アクセスまたはその試み</li><li>サービスへ過度な負荷を与える行為</li><li>利用回数制限等を不正に回避する行為</li><li>自動化された大量アクセス等により通常利用を超えてサービスを使用する行為</li><li>本サービスまたは他の利用者の利用を妨害する行為</li><li>リバースエンジニアリングその他法令上認められない解析行為</li><li>有害なプログラム等を送信する行為</li><li>第三者の個人情報や機密情報を権限なく処理させる行為</li><li>本サービスを違法または不正な目的で利用する行為</li><li>その他、運営者が不適切と合理的に判断する行為</li></ul></section>
                <section id="free"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第9条　Freeプラン</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>Freeプランは無料で利用できます。</li><li>現在のFreeプランの主なAI解析上限は以下のとおりです。<dl class="mt-3 space-y-2"><div><dt class="font-semibold text-[#171717] dark:text-white">Web解析：</dt><dd>月100回</dd></div><div><dt class="font-semibold text-[#171717] dark:text-white">スクリーンショット解析：</dt><dd>月100回</dd></div></dl></li><li>Web解析とスクリーンショット解析は別々にカウントされます。</li><li>利用枠は原則として毎月1日に更新されます。</li><li>利用上限、対象機能その他Freeプランの内容は、サービス運営上必要な場合に変更されることがあります。</li><li>重要な変更を行う場合は、適切な方法で利用者へ案内します。</li></ol></section>
                <section id="plus"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第10条　Plusプラン</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>Plusは有料の月額サブスクリプションです。</li><li>現在のPlus料金は以下のとおりです。<dl class="mt-3 space-y-2"><div><dt class="font-semibold text-[#171717] dark:text-white">日本円：</dt><dd>月額300円</dd></div><div><dt class="font-semibold text-[#171717] dark:text-white">米ドル：</dt><dd>月額1.99米ドル</dd></div></dl></li><li>選択した通貨に対応する料金が適用されます。</li><li>Plusの主なAI解析上限は以下のとおりです。<dl class="mt-3 space-y-2"><div><dt class="font-semibold text-[#171717] dark:text-white">Web解析：</dt><dd>月1,000回</dd></div><div><dt class="font-semibold text-[#171717] dark:text-white">スクリーンショット解析：</dt><dd>月1,000回</dd></div></dl></li><li>Web解析とスクリーンショット解析は別々にカウントされます。</li><li>利用枠は原則として毎月1日に更新されます。</li><li>Plus料金には、利用者の通信費その他本サービス外で発生する費用は含まれません。</li></ol></section>
                <section id="renewal"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第11条　Plusの契約および自動更新</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>PlusはStripeを利用した月額契約です。</li><li>利用者がPlusを申し込み、Stripeによる決済手続が正常に完了した時点からPlusを利用できます。</li><li>Plusは、利用者が解約手続を行わない限り、契約期間終了時に自動的に翌期間へ更新されます。</li><li>次回の料金は、Stripeで登録された支払方法により請求されます。</li><li>支払いが正常に完了しない場合、Plus機能の全部または一部を利用できなくなる場合があります。</li></ol></section>
                <section id="cancellation"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第12条　Plusの解約</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>利用者は、本サービスから案内するStripe Customer Portal等を利用してPlusを解約できます。</li><li>解約手続を行った場合でも、現在の支払済み契約期間が終了するまではPlusを利用できます。</li><li>契約期間終了後は、原則としてFreeプランへ移行します。</li><li>解約手続を行っても、利用者の学習セット、問題、復習履歴等が直ちに削除されるものではありません。</li></ol></section>
                <section id="refunds"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第13条　返金</h2><p class="mt-5">返金、二重決済、誤決済その他支払済み料金の取扱いについては、本サービス上の特定商取引法に基づく表記その他の個別表示に従うものとします。</p>{{-- TODO: 公開前に返金ポリシーを確定すること。勝手に「返金不可」等へ変更しないこと。特商法ページおよびStripe Checkout直前表示と統一すること。 --}}</section>
                <section id="payment"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第14条　決済</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>Plusの決済にはStripeを利用します。</li><li>Stripeによる決済については、Stripeの利用条件およびプライバシーポリシー等も適用されます。</li><li>クレジットカード番号全体、CVC等についてはStripeが提供する決済画面で処理されます。</li><li>利用者は、正当な権限を有する支払方法を利用してください。</li></ol></section>
                <section id="changes"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第15条　サービスの変更・停止</h2><p class="mt-5">運営者は、以下の場合、本サービスの全部または一部を変更、一時停止または終了することがあります。</p><ul class="mt-4 list-disc space-y-1 pl-6"><li>システム保守を行う場合</li><li>セキュリティ上必要な場合</li><li>外部サービスに障害・仕様変更等が発生した場合</li><li>災害、通信障害その他不可抗力が発生した場合</li><li>その他サービス提供が困難になった場合</li></ul><p class="mt-4">可能な場合には、事前または事後に本サービス上で案内します。</p></section>
                <section id="external"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第16条　外部サービス</h2><p class="mt-5">本サービスでは、Google、Google Gemini API、Stripe、OpenAI ChatGPT等の第三者サービスを利用することがあります。</p><p class="mt-4">外部サービスの障害、仕様変更、サービス終了等により、本サービスの一部機能へ影響が生じる場合があります。</p></section>
                <section id="intellectual-property"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第17条　知的財産権</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>本サービスそのものに関するプログラム、デザイン、ロゴ、文章その他の権利は、運営者または正当な権利者に帰属します。</li><li>利用者が本サービスへ入力した情報について、利用者または元の権利者が有する権利が本サービスの利用によって当然に運営者へ移転するものではありません。</li><li>運営者は、本サービスを提供するために必要な範囲でのみ利用者が入力した情報を処理します。</li></ol></section>
                <section id="restriction"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第18条　利用制限・アカウント停止</h2><p class="mt-5">運営者は、利用者が以下に該当する場合、必要な範囲で利用を制限し、またはアカウントを停止することがあります。</p><ul class="mt-4 list-disc space-y-1 pl-6"><li>本規約に違反した場合</li><li>不正利用が確認された場合</li><li>サービスまたは他の利用者へ重大な影響を与えた場合</li><li>料金の支払いが正常に行われない場合</li><li>その他サービス運営上重大な問題がある場合</li></ul><p class="mt-4">必要以上に利用者の権利を制限しないよう、合理的な範囲で対応します。</p></section>
                <section id="deletion"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第19条　アカウント削除</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>利用者は、本サービスが提供する方法によりアカウント削除を申請できます。</li><li>Plus契約中にアカウントを削除する場合は、Plus契約の終了処理が必要となる場合があります。</li><li>アカウント削除後のデータの取扱いについては、プライバシーポリシーに従います。</li><li>法令上保存が必要な情報その他正当な理由により保持する必要がある情報については、削除後も一定期間保持する場合があります。</li></ol></section>
                <section id="disclaimer"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第20条　免責等</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>運営者は、本サービスが常に中断なく利用できること、エラーが存在しないこと、AI生成内容が常に正確であることを保証しません。</li><li>運営者は、外部サービス、通信環境、利用者の端末、Webサイト側の仕様等に起因する障害について、運営者の責めに帰すべき場合を除き、その発生を完全に防止することを保証しません。</li><li>本条その他本規約の規定は、消費者契約法その他の法令により運営者が負う責任を不当に免除するものではありません。</li></ol></section>
                <section id="privacy"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第21条　プライバシー</h2><p class="mt-5">本サービスにおける利用者情報の取扱いについては、別途定める<a href="{{ route('privacy') }}" class="font-medium text-[#3155D9] underline decoration-[#3155D9]/30 underline-offset-4 transition hover:text-[#2848bd] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9]">プライバシーポリシー</a>によります。</p></section>
                <section id="terms-changes"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第22条　本規約の変更</h2><ol class="mt-5 list-decimal space-y-4 pl-6"><li>運営者は、法令の改正、サービス内容の変更その他必要な場合に本規約を変更することがあります。</li><li>利用者に重大な影響を与える変更を行う場合には、本サービス上その他適切な方法で内容および適用時期を案内します。</li></ol></section>
                <section id="severability"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第23条　分離可能性</h2><p class="mt-5">本規約の一部が法令等により無効または執行不能と判断された場合でも、その他の部分は引き続き有効とします。</p></section>
                <section id="governing-law"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第24条　準拠法</h2><p class="mt-5">本規約は日本法に準拠します。</p></section>
                <section id="jurisdiction"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第25条　管轄</h2><p class="mt-5">本サービスに関して紛争が生じた場合の合意管轄裁判所については、運営者の所在地その他の事情を踏まえ、公開前に適切な内容を確定します。</p>{{-- TODO: 運営者情報確定後、管轄裁判所条項を法的に確認して設定すること。 --}}</section>
                <section id="contact"><h2 class="text-2xl font-semibold tracking-tight text-[#171717] dark:text-white">第26条　お問い合わせ</h2><p class="mt-5">本規約に関するお問い合わせは、以下の窓口までご連絡ください。</p><p class="mt-5"><span class="font-semibold text-[#171717] dark:text-white">サービス名：</span>Web Learning</p>{{-- TODO: 公開前に運営者名を設定 --}}{{-- TODO: 公開前に問い合わせメールアドレスを設定 --}}{{-- TODO: 公開前に所在地を設定 --}}</section>
            </div>
        </article></main>
        <footer class="border-t border-stone-200 px-5 py-8 dark:border-stone-800 sm:px-8"><nav class="mx-auto flex max-w-3xl flex-wrap justify-center gap-x-5 gap-y-2 text-xs" aria-label="法務ページ"><a href="{{ route('terms') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">利用規約</a><a href="{{ route('privacy') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">プライバシーポリシー</a><a href="{{ route('tokushoho') }}" class="text-stone-500 underline decoration-stone-300 underline-offset-4 transition hover:text-[#3155D9] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#3155D9] dark:text-stone-400">特定商取引法に基づく表記</a></nav></footer>
    </body>
</html>
