<?php

use App\Http\Controllers\AiUsageController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\CollectionLearningSetController;
use App\Http\Controllers\ExtensionCaptureController;
use App\Http\Controllers\ExtensionPageController;
use App\Http\Controllers\ExtensionPairingController;
use App\Http\Controllers\ExtensionQuizController;
use App\Http\Controllers\LearningAiController;
use App\Http\Controllers\LearningCaptureController;
use App\Http\Controllers\LearningCollectionController;
use App\Http\Controllers\LearningSetController;
use App\Http\Controllers\LearningStatsController;
use App\Http\Controllers\LearningTermBoxController;
use App\Http\Controllers\LearningTermBoxMembershipController;
use App\Http\Controllers\LearningTermController;
use App\Http\Controllers\OnboardingController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\ScreenshotLearningController;
use App\Http\Controllers\StudyModeController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::view('/privacy', 'privacy')->name('privacy');
Route::view('/terms', 'terms')->name('terms');
Route::view('/tokushoho', 'tokushoho')->name('tokushoho');

Route::get('/dashboard', [LearningSetController::class, 'index'])->middleware(['auth', 'verified'])->name('dashboard');
Route::get('/onboarding', [OnboardingController::class, 'show'])->name('onboarding.show');

Route::post('/extension/analyze-page', [ExtensionPageController::class, 'analyze'])->middleware('throttle:30,1')->name('extension.analyze-page');
Route::post('/extension/generate-quiz', [ExtensionQuizController::class, 'generate'])->middleware('throttle:10,1')->name('extension.generate-quiz');
Route::post('/extension/captures', [ExtensionCaptureController::class, 'store'])->middleware('throttle:30,1')->name('extension.captures.store');
Route::post('/extension/pairings', [ExtensionPairingController::class, 'start'])->middleware('throttle:10,1')->name('extension.pairings.start');
Route::post('/extension/pairings/{pairingId}/claim', [ExtensionPairingController::class, 'claim'])->middleware('throttle:30,1')->name('extension.pairings.claim');
Route::get('/extension/connection', [ExtensionPairingController::class, 'status'])->middleware('throttle:30,1')->name('extension.connection.show');
Route::delete('/extension/connection', [ExtensionPairingController::class, 'disconnect'])->middleware('throttle:10,1')->name('extension.connection.destroy');
Route::get('/extension/connect/{pairingId}', [ExtensionPairingController::class, 'show'])->name('extension.connect.show');

Route::middleware('auth')->group(function () {
    Route::get('/pricing', [BillingController::class, 'pricing'])->name('pricing');
    Route::get('/billing/confirm', [BillingController::class, 'confirm'])->name('billing.confirm');
    Route::post('/billing/checkout', [BillingController::class, 'checkout'])->name('billing.checkout');
    Route::get('/billing/success', [BillingController::class, 'success'])->name('billing.success');
    Route::get('/billing/cancel', [BillingController::class, 'cancel'])->name('billing.cancel');
    Route::post('/billing/portal', [BillingController::class, 'portal'])->name('billing.portal');
    Route::get('/extension/connect/{pairingId}/authorize', [ExtensionPairingController::class, 'authorizePairing'])->name('extension.connect.authorize');
    Route::post('/extension/connect/{pairingId}', [ExtensionPairingController::class, 'approve'])->name('extension.connect.approve');
    Route::post('/onboarding/complete', [OnboardingController::class, 'complete'])->name('onboarding.complete');
    Route::get('/captures', [LearningCaptureController::class, 'index'])->name('captures.index');
    Route::get('/captures/{capture}', [LearningCaptureController::class, 'show'])->name('captures.show');
    Route::post('/captures/{capture}/generate', [LearningCaptureController::class, 'generate'])->name('captures.generate');
    Route::delete('/captures/{capture}', [LearningCaptureController::class, 'destroy'])->name('captures.destroy');
    Route::post('/profile/extension-token', [ProfileController::class, 'createExtensionToken'])->name('profile.extension-token.create');
    Route::delete('/profile/extension-token', [ProfileController::class, 'destroyExtensionToken'])->name('profile.extension-token.destroy');
    Route::get('/learning-stats', [LearningStatsController::class, 'index'])->name('learning-stats.index');
    Route::get('/reviews/today', [ReviewController::class, 'today'])->name('reviews.today');
    Route::post('/reviews/today', [ReviewController::class, 'grade'])->name('reviews.grade');
    Route::get('/reviews/today/result', [ReviewController::class, 'result'])->name('reviews.result');
    Route::get('/screenshot-learning', [ScreenshotLearningController::class, 'create'])->name('screenshot-learning.create');
    Route::post('/screenshot-learning', [ScreenshotLearningController::class, 'analyze'])->name('screenshot-learning.analyze');
    Route::get('/screenshot-learning/{token}/candidates', [ScreenshotLearningController::class, 'candidates'])->name('screenshot-learning.candidates');
    Route::post('/screenshot-learning/{token}/generate', [ScreenshotLearningController::class, 'generate'])->name('screenshot-learning.generate');
    Route::get('/study-mode', [StudyModeController::class, 'index'])->name('study-mode.index');
    Route::get('/study-mode/input', [StudyModeController::class, 'configure'])->defaults('mode', 'input')->name('study-mode.input');
    Route::get('/study-mode/random', [StudyModeController::class, 'configure'])->defaults('mode', 'random')->name('study-mode.random');
    Route::post('/study-mode/{mode}/start', [StudyModeController::class, 'start'])->name('study-mode.start');
    Route::get('/study-mode/play', [StudyModeController::class, 'play'])->name('study-mode.play');
    Route::post('/study-mode/answer', [StudyModeController::class, 'answer'])->name('study-mode.answer');
    Route::post('/study-mode/next', [StudyModeController::class, 'next'])->name('study-mode.next');
    Route::get('/study-mode/result', [StudyModeController::class, 'result'])->name('study-mode.result');
    Route::get('/collections', [LearningCollectionController::class, 'index'])->name('collections.index');
    Route::post('/collections', [LearningCollectionController::class, 'store'])->name('collections.store');
    Route::post('/collections/auto-organize', [LearningCollectionController::class, 'autoOrganize'])->name('collections.auto-organize');
    Route::get('/collections/deleted', [LearningCollectionController::class, 'deleted'])->name('collections.deleted');
    Route::post('/collections/deleted/{collection}/restore', [LearningCollectionController::class, 'restore'])->name('collections.restore');
    Route::get('/collections/{collection}', [LearningCollectionController::class, 'show'])->name('collections.show');
    Route::patch('/collections/{collection}', [LearningCollectionController::class, 'update'])->name('collections.update');
    Route::delete('/collections/{collection}', [LearningCollectionController::class, 'destroy'])->name('collections.destroy');
    Route::delete('/collections/{collection}/learning-sets/{learningSet}', [CollectionLearningSetController::class, 'destroy'])->name('collections.learning-sets.destroy');
    Route::get('/extension-quiz-drafts/{token}/quiz', [ExtensionQuizController::class, 'quiz'])->name('extension-quiz-drafts.quiz');
    Route::post('/extension-quiz-drafts/{token}/quiz', [ExtensionQuizController::class, 'grade'])->name('extension-quiz-drafts.grade');
    Route::get('/extension-quiz-drafts/{token}/result', [ExtensionQuizController::class, 'result'])->name('extension-quiz-drafts.result');
    Route::post('/extension-quiz-drafts/{token}/save', [ExtensionQuizController::class, 'save'])->name('extension-quiz-drafts.save');
    Route::get('/ai-usage', [AiUsageController::class, 'index'])->name('ai-usage.index');
    Route::post('/learning-ai/ask', [LearningAiController::class, 'ask'])->middleware('throttle:12,1')->name('learning-ai.ask');
    Route::get('/learning-terms', [LearningTermController::class, 'index'])->name('learning-terms.index');
    Route::post('/learning-terms', [LearningTermController::class, 'store'])->middleware('throttle:20,1')->name('learning-terms.store');
    Route::post('/learning-terms/bulk-categories', [LearningTermBoxMembershipController::class, 'bulkUpdate'])->name('learning-terms.bulk-categories.update');
    Route::put('/learning-terms/{learningTerm}/boxes', [LearningTermBoxMembershipController::class, 'update'])->name('learning-terms.boxes.update');
    Route::get('/learning-terms/{learningTerm}/edit', [LearningTermController::class, 'edit'])->name('learning-terms.edit');
    Route::patch('/learning-terms/{learningTerm}', [LearningTermController::class, 'update'])->name('learning-terms.update');
    Route::delete('/learning-terms/{learningTerm}', [LearningTermController::class, 'destroy'])->name('learning-terms.destroy');
    Route::patch('/learning-terms/{learningTerm}/restore', [LearningTermController::class, 'restore'])->name('learning-terms.restore');
    Route::post('/learning-term-boxes', [LearningTermBoxController::class, 'store'])->name('learning-term-boxes.store');
    Route::patch('/learning-term-boxes/{learningTermBox}', [LearningTermBoxController::class, 'update'])->name('learning-term-boxes.update');
    Route::delete('/learning-term-boxes/{learningTermBox}', [LearningTermBoxController::class, 'destroy'])->name('learning-term-boxes.destroy');
    Route::put('/learning-term-boxes/{learningTermBox}/terms', [LearningTermBoxMembershipController::class, 'addTerms'])->name('learning-term-boxes.terms.update');
    Route::delete('/learning-term-boxes/{learningTermBox}/terms/{learningTerm}', [LearningTermBoxMembershipController::class, 'destroy'])->name('learning-term-boxes.terms.destroy');
    Route::get('/learning-sets/create', [LearningSetController::class, 'create'])->name('learning-sets.create');
    Route::post('/learning-sets', [LearningSetController::class, 'store'])->name('learning-sets.store');
    Route::put('/learning-sets/{learningSet}/collections', [CollectionLearningSetController::class, 'update'])->name('learning-sets.collections.update');
    Route::delete('/learning-sets/{learningSet}', [LearningSetController::class, 'destroy'])->name('learning-sets.destroy');
    Route::post('/learning-sets/deleted/{learningSet}/restore', [LearningSetController::class, 'restore'])->name('learning-sets.restore');
    Route::get('/learning-sets/{learningSet}/questions/create', [QuestionController::class, 'create'])->name('learning-sets.questions.create');
    Route::post('/learning-sets/{learningSet}/questions', [QuestionController::class, 'store'])->name('learning-sets.questions.store');
    Route::get('/learning-sets/{learningSet}/quiz', [LearningSetController::class, 'quiz'])->name('learning-sets.quiz');
    Route::post('/learning-sets/{learningSet}/quiz', [LearningSetController::class, 'grade'])->name('learning-sets.quiz.grade');
    Route::post('/learning-sets/{learningSet}/quiz/restart', [LearningSetController::class, 'restart'])->name('learning-sets.quiz.restart');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
